name: Docker FunClip Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'é€‰æ‹©ç¼–è¯‘å¹³å°'
        required: true
        default: 'ALL'
        type: choice
        options:
          - ALL
          - AMD64
          - ARM64
      tag:
        description: 'é•œåƒæ ‡ç­¾ (å¯é€‰ï¼Œé»˜è®¤ä½¿ç”¨latest)'
        required: false
        default: 'latest'
        type: string

jobs:
  build-funclip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set platform value
        id: set_platform
        run: |
          case "${{ github.event.inputs.platform }}" in
            AMD64)
              echo "platforms=linux/amd64" >> "$GITHUB_OUTPUT"
              ;;
            ARM64)
              echo "platforms=linux/arm64" >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "platforms=linux/amd64,linux/arm64" >> "$GITHUB_OUTPUT"
              ;;
          esac

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push FunClip
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ steps.set_platform.outputs.platforms }}
          push: true
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/funclip:${{ github.event.inputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/funclip:${{ steps.date.outputs.date }}
            ${{ secrets.DOCKERHUB_USERNAME }}/funclip:latest

      - name: Image digest
        run: echo "Image pushed successfully! ðŸŽ‰"